"""Aggregate result CSVs into RESULTS.md tables + figures.

Usage: python scripts/make_report.py
"""
from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

from windml.config import ARTIFACTS, REPO_ROOT

RESULTS = ARTIFACTS / "results"
FIGURES = ARTIFACTS / "figures"

HEADLINE_VARS = ["u10", "v10", "wind_speed", "u850", "v850", "z500", "t2m"]
HEADLINE_LEADS = [24, 72, 120]
UNITS = {
    "u10": "m/s", "v10": "m/s", "wind_speed": "m/s", "u850": "m/s", "v850": "m/s",
    "t850": "K", "z500": "m²/s²", "t2m": "K", "msl": "Pa",
}
# display order: baselines, our models, then competitors
ORDER_HINT = [
    "persistence", "climatology", "linear",
    "unet", "vit", "afno", "graph",
    "unet_ft", "vit_ft", "afno_ft",
    "hres_2020", "pangu_2020", "graphcast_2020", "gencast_mean_2020",
]


def load_all(pattern: str = "*_test.csv") -> pd.DataFrame:
    frames = [pd.read_csv(csv) for csv in sorted(RESULTS.glob(pattern))]
    if not frames:
        return pd.DataFrame()
    df = pd.concat(frames, ignore_index=True)
    order = {name: i for i, name in enumerate(ORDER_HINT)}
    df["order"] = df.model.map(lambda m: order.get(m, 99))
    return df.sort_values(["order", "model"])


def acc_table(df: pd.DataFrame, variable: str) -> pd.DataFrame:
    sub = df[(df.variable == variable) & (df.lead_h.isin(HEADLINE_LEADS))]
    tab = sub.pivot_table(index=["order", "model"], columns="lead_h", values="acc")
    tab.index = tab.index.droplevel(0)
    return tab.round(3)


def skill_summary(df: pd.DataFrame, reference: str = "graphcast_2020") -> pd.DataFrame:
    """Percent RMSE change vs a reference model (negative = better)."""
    if reference not in set(df.model):
        return pd.DataFrame()
    ref = df[df.model == reference].set_index(["variable", "lead_h"]).rmse
    rows = []
    for model, grp in df.groupby("model", sort=False):
        if model == reference:
            continue
        g = grp.set_index(["variable", "lead_h"]).rmse
        common = g.index.intersection(ref.index)
        if not len(common):
            continue
        rel = (g.loc[common] / ref.loc[common] - 1.0) * 100
        rec = {"model": model}
        for var in ["u10", "v10", "wind_speed"]:
            for lead in HEADLINE_LEADS:
                if (var, lead) in rel.index:
                    rec[f"{var}@{lead}h"] = round(float(rel.loc[(var, lead)]), 1)
        rows.append(rec)
    return pd.DataFrame(rows).set_index("model")


def rmse_table(df: pd.DataFrame, variable: str) -> pd.DataFrame:
    sub = df[(df.variable == variable) & (df.lead_h.isin(HEADLINE_LEADS))]
    tab = sub.pivot_table(index=["order", "model"], columns="lead_h", values="rmse")
    tab.index = tab.index.droplevel(0)
    return tab.round(3)


def curves_figure(df: pd.DataFrame, variables: list[str], out: Path) -> None:
    fig, axes = plt.subplots(1, len(variables), figsize=(5 * len(variables), 4))
    for ax, var in zip(axes, variables):
        sub = df[df.variable == var]
        for model, grp in sub.groupby("model", sort=False):
            grp = grp.sort_values("lead_h")
            ax.plot(grp.lead_h, grp.rmse, label=model, marker=".", ms=4)
        ax.set_title(var)
        ax.set_xlabel("lead time (h)")
        ax.set_ylabel(f"RMSE ({UNITS.get(var, '')})")
        ax.grid(alpha=0.3)
    axes[-1].legend(fontsize=7, loc="upper left")
    fig.tight_layout()
    FIGURES.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=140)
    plt.close(fig)


def main() -> None:
    df = load_all()
    lines = [
        "# Results",
        "",
        "*Generated by `scripts/make_report.py`. Latitude-weighted RMSE on 2020,",
        "00/12 UTC init times, verified against ERA5 at 64x32 (5.625 deg).*",
        "",
        "Competitor rows (`graphcast_2020`, `pangu_2020`, `hres_2020`,",
        "`gencast_mean_2020`) are the models' published forecasts regridded by",
        "WeatherBench 2 to 64x32 and scored with the identical pipeline. They were",
        "produced at 0.25 deg with vastly more compute; our from-scratch models",
        "(unet/vit/afno/graph) train on 4 CPU cores at 5.625 deg. The comparable",
        "published anchor at this resolution is Rasp & Thuerey 2021 (ResNet):",
        "z500 RMSE 268/499 m2/s2 at 3/5 days.",
        "",
    ]
    for var in HEADLINE_VARS:
        tab = rmse_table(df, var)
        if tab.empty:
            continue
        lines.append(f"## {var} — RMSE ({UNITS.get(var, '')}) at 24/72/120 h")
        lines.append("")
        lines.append(tab.to_markdown())
        lines.append("")

    acc = acc_table(df, "wind_speed")
    if not acc.empty:
        lines += ["## 10m wind speed — ACC at 24/72/120 h", "", acc.to_markdown(), ""]

    skill = skill_summary(df)
    if not skill.empty:
        lines += [
            "## Wind RMSE relative to GraphCast (%, negative = better)",
            "",
            skill.to_markdown(),
            "",
        ]

    crps = load_all("*_crps.csv")
    if not crps.empty:
        sub = crps[crps.variable.isin(["u10", "v10", "wind_speed"])
                   & crps.lead_h.isin(HEADLINE_LEADS)]
        tab = sub.pivot_table(index="model", columns=["variable", "lead_h"], values="crps")
        lines += ["## Probabilistic: wind CRPS (m/s)", "", tab.round(3).to_markdown(), ""]

    curves_figure(df, ["u10", "wind_speed", "z500"], FIGURES / "rmse_curves.png")
    lines.append("![RMSE curves](artifacts/figures/rmse_curves.png)")
    lines.append("")

    (REPO_ROOT / "RESULTS.md").write_text("\n".join(lines))
    print(f"wrote {REPO_ROOT / 'RESULTS.md'} with {df.model.nunique()} models")


if __name__ == "__main__":
    main()
